config/routes.rb
TrocaLivro::Application.routes.draw do
  resources :trocas

  resources :usuariolivros

  devise_for :users

  get "pages/index"

  get "login/login"

  resources :livro_bancos

  resources :usuarios
  

  

	match ':controller(/:action(/:id))(.:format)'
	root :to => "geral#index"
end

app/models/usuariolivro.rb
class Usuariolivro < ActiveRecord::Base
  attr_accessible :comentario, :user_id, :livro_banco_id
  
  belongs_to :livro_banco
end

app/controllers/usuariolivros_controller.rb
	class UsuariolivrosController < ApplicationController
  # GET /usuariolivros
  # GET /usuariolivros.json
  def index
    @usuariolivros = Usuariolivro.where({id_usuario: params[:id]})
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuariolivros }
    end
  end

  # GET /usuariolivros/1
  # GET /usuariolivros/1.json
  def show
    @usuariolivro = Usuariolivro.new
	@usuariolivro.user_id = current_user.id
	@usuariolivro.livro_banco_id = params[:id]
	@usuariolivro.save
	respond_to do |format|
      format.html { redirect_to usuariolivros_url }
    end
  end

  # GET /usuariolivros/new
  # GET /usuariolivros/new.json
  def new
    @livros = LivroBanco.all
	respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuariolivro }
    end
  end

  # GET /usuariolivros/1/edit
  def edit
    @usuariolivro = Usuariolivro.find(params[:id])
  end

  # POST /usuariolivros
  # POST /usuariolivros.json
  def create
    @usuariolivro = Usuariolivro.new(params[:usuariolivro])

    respond_to do |format|
      if @usuariolivro.save
        format.html { redirect_to @usuariolivro, notice: 'Livro adicionado na sua lista com sucesso.' }
        format.json { render json: @usuariolivro, status: :created, location: @usuariolivro }
      else
        format.html { render action: "new" }
        format.json { render json: @usuariolivro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuariolivros/1
  # PUT /usuariolivros/1.json
  def update
  end

  # DELETE /usuariolivros/1
  # DELETE /usuariolivros/1.json
  def destroy
    @livro = Usuariolivro.where({livro_banco_id: params[:id] , user_id: current_user.id})
    @livro[0].destroy

    respond_to do |format|
      format.html { redirect_to usuariolivros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usuariolivros_helper.rb
module UsuariolivrosHelper
end

app/views/usuariolivros/_form.html.erb
<table border="0">
  <tr>
    <th>Capa</th>
    <th>Isbn</th>
    <th>Titulo</th>
    <th>Autor</th>
    <th>Editora</th>
    <th></th>
    <th></th>
  </tr>
<% if !@livros.nil? %>
<% @livros.each do |livro| %>
  <tr>
	<td><%= image_tag livro.foto.url(:thumb) %></td>
    <td><%= livro.isbn %></td>
    <td><%= livro.titulo %></td>
    <td><%= livro.autor %></td>
    <td><%= livro.editora %></td>
	<td><a href="/usuariolivros/<%= livro.id %>">Adicionar na lista</a></td>
  </tr>
<% end %>
<% end %>
</table>

app/views/usuariolivros/_form.html_bkp.erb
<%= form_for(@usuariolivro) do |f| %>
  <% if @usuariolivro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuariolivro.errors.count, "error") %> prohibited this usuariolivro from being saved:</h2>
      <ul>
      <% @usuariolivro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<input type='hidden' name='usuariolivro[user_id]' value="<%= current_user.id %>"/>
  </div>
  <div class="field">
    <%= f.label :Nome %><br />
	<%= f.collection_select(:livro_banco_id, LivroBanco.order("titulo"), :id, :titulo, {:prompt => "Selecione o livro"}) %>
  </div>
  <div class="field">
    <%= f.label :comentário %><br />
    <%= f.text_field :comentario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuariolivros/edit.html.erb
<h1>Editing usuariolivro</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuariolivro %> |
<%= link_to 'Back', usuariolivros_path %>

app/views/usuariolivros/index.html.erb
<h1>Seus livros</h1>

<table>
  <tr>
	<th>Capa</th>
    <th>Isbn</th>
    <th>Titulo</th>
    <th>Autor</th>
    <th>Editora</th>
  </tr>
<% 
	@usuariolivros = Usuariolivro.where({user_id: current_user.id})
	if !@usuariolivros.empty?
		@livros = LivroBanco.find([@usuariolivros.all(:select => :livro_banco_id).collect(&:livro_banco_id)])
	end
%>
<% 
 if !@usuariolivros.empty?
 @livros.each do |livro| %>
  <tr>
  	<td><%= image_tag livro.foto.url(:thumb) %></td>
    <td><%= livro.isbn %></td>
    <td><%= livro.titulo %></td>
    <td><%= livro.autor %></td>
    <td><%= livro.editora %></td>
	<td><a href="/usuariolivros/<%= livro.id %>" data-confirm="Tem certeza?" class="Usuariolivro" data-method="delete" rel="nofollow">Remover da lista</a></td>
  </tr>
<% end %>
<% end %>
</table>

app/views/usuariolivros/new.html.erb
<h1>Novo Livro</h1>

<%= render 'form' %>

app/views/usuariolivros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @livro.titulo %>
</p>

<p>
  <b>Comentário:</b>
  <%= @usuariolivro.comentario %>
</p>