config/routes.rb
TrocaLivro::Application.routes.draw do
  resources :trocas

  resources :usuariolivros

  devise_for :users

  get "pages/index"

  get "login/login"

  resources :livro_bancos

  resources :usuarios
  

  

	match ':controller(/:action(/:id))(.:format)'
	root :to => "geral#index"
end

app/controllers/livro_usuario_controller.rb
class LivroUsuarioController < ApplicationController

  # GET /livro_usuarios
  # GET /livro_usuarios.json
  def index
  
    @livro_usuarios = LivroUsuario.all
	respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @livro_usuarios }
    end
  end

  # GET /livro_usuarios/1
  # GET /livro_usuarios/1.json
  def show
    @livro_banco = LivroUsuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @livro_banco }
    end
  end

  # GET /livro_usuarios/new
  # GET /livro_usuarios/new.json
  def new
    @livro_banco = LivroUsuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @livro_banco }
    end
  end

  # GET /livro_usuarios/1/edit
  def edit
    @livro_banco = LivroUsuario.find(params[:id])
  end

  # POST /livro_usuarios
  # POST /livro_usuarios.json
  def create
    @livro_banco = LivroUsuario.new(params[:livro_banco])

    respond_to do |format|
      if @livro_banco.save
        format.html { redirect_to @livro_banco, notice: 'Livro criado com sucesso.' }
        format.json { render json: @livro_banco, status: :created, location: @livro_banco }
      else
        format.html { render action: "new" }
        format.json { render json: @livro_banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /livro_usuarios/1
  # PUT /livro_usuarios/1.json
  def update
    @livro_banco = LivroUsuario.find(params[:id])

    respond_to do |format|
      if @livro_banco.update_attributes(params[:livro_banco])
        format.html { redirect_to @livro_banco, notice: 'Livro editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @livro_banco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livro_usuarios/1
  # DELETE /livro_usuarios/1.json
  def destroy
    @livro_banco = LivroUsuario.find(params[:id])
    @livro_banco.destroy

    respond_to do |format|
      format.html { redirect_to livro_usuarios_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/livro_usuario_helper.rb
module LivroUsuarioHelper
end

app/views/livro_usuario/_form.html.erb
<%= form_for(@livro_banco) do |f| %>
  <% if @livro_banco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro_banco.errors.count, "error") %> prohibited this livro_banco from being saved:</h2>
      <ul>
      <% @livro_banco.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :editora %><br />
    <%= f.text_field :editora %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/livro_usuario/edit.html.erb
<h1>Editar livro</h1>

<%= render 'form' %>

app/views/livro_usuario/index.html.erb
<h1>Lista de livros</h1>

<table>
  <tr>
    <th>Isbn</th>
    <th>Titulo</th>
    <th>Autor</th>
    <th>Editora</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @livro_bancos.each do |livro_banco| %>
  <tr>
    <td><%= livro_banco.isbn %></td>
    <td><%= livro_banco.titulo %></td>
    <td><%= livro_banco.autor %></td>
    <td><%= livro_banco.editora %></td>
  </tr>
<% end %>
</table>

app/views/livro_usuario/new.html.erb
<h1>Novo livro</h1>

<%= render 'form' %>

app/views/livro_usuario/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Isbn:</b>
  <%= @livro_banco.isbn %>
</p>

<p>
  <b>Titulo:</b>
  <%= @livro_banco.titulo %>
</p>

<p>
  <b>Autor:</b>
  <%= @livro_banco.autor %>
</p>

<p>
  <b>Editora:</b>
  <%= @livro_banco.editora %>
</p>


<%= link_to 'Editar', edit_livro_banco_path(@livro_banco) %> |
<%= link_to 'Voltar', livro_bancos_path %>