config/routes.rb
TrocaLivro::Application.routes.draw do
  resources :trocas

  resources :usuariolivros

  devise_for :users

  get "pages/index"

  get "login/login"

  resources :livro_bancos

  resources :usuarios
  

  

	match ':controller(/:action(/:id))(.:format)'
	root :to => "geral#index"
end

app/models/troca.rb
class Troca < ActiveRecord::Base
  attr_accessible :usuarioSolicitante_id, :livroSolicitante_id, :usuarioSolicitado_id, :livroSolicitado_id, :comentario, :status

end

app/controllers/trocas_controller.rb
class TrocasController < ApplicationController
  # GET /trocas
  # GET /trocas.json
  def index
    @trocas = Troca.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trocas }
    end
  end

  # GET /trocas/1
  # GET /trocas/1.json
  def show
    @troca = Troca.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @troca }
    end
  end

  # GET /trocas/new
  # GET /trocas/new.json
  def new
    @troca = Troca.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @troca }
    end
  end

  # GET /trocas/1/edit
  def edit
    @troca = Troca.find(params[:id])
	@troca.status = "1"
	@troca.save
	render action: "show"
  end

  # POST /trocas
  # POST /trocas.json
  def create
	@troca = Troca.new(params[:troca])
	idUsuario = Usuariolivro.where({livro_banco_id: @troca.livroSolicitado_id})[0].user_id
	@troca.usuarioSolicitante_id = current_user.id
	@troca.usuarioSolicitado_id = idUsuario
	@troca.status = "0"
	respond_to do |format|
      if @troca.save
        format.html { redirect_to @troca, notice: 'Solicitação de troca foi criada com sucesso.' }
        format.json { render json: @troca, status: :created, location: @troca }
      else
        format.html { render action: "new" }
        format.json { render json: @troca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trocas/1
  # PUT /trocas/1.json
  def update
    @trocas = Troca.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trocas }
    end
  end

  # DELETE /trocas/1
  # DELETE /trocas/1.json
  def destroy
    @troca = Troca.find(params[:id])
    @troca.destroy

    respond_to do |format|
      format.html { redirect_to trocas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trocas_helper.rb
module TrocasHelper
end

app/views/trocas/_form.html.erb
<%= form_for(@troca) do |f| %>
	<% if @troca.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@troca.errors.count, "error") %> prohibited this troca from being saved:</h2>
			<ul>
				<% @troca.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%
		if !Usuariolivro.all.collect(&:livro_banco_id).empty?
			@livro_bancos = LivroBanco.find([Usuariolivro.all.collect(&:livro_banco_id)])
			@usuariolivros = Usuariolivro.where({user_id: current_user.id})
			if !@usuariolivros.empty?
				@livros = LivroBanco.find([@usuariolivros.all(:select => :livro_banco_id).collect(&:livro_banco_id)])
			end
	%>
	<div class="field">
		<%= f.label :Seu_Livro %><br />
		<%= f.collection_select(:livroSolicitante_id, @livros, :id, :titulo, {:prompt => "Selecione seu livro"}) %>
	</div>
	<div class="field">
		<%= f.label :Livro_Desejado %><br />
		<%= f.collection_select(:livroSolicitado_id, @livro_bancos, :id, :titulo, {:prompt => "Selecione o livro desejado"}) %>
	</div>
	<div class="field">
		<%= f.label :comentário %><br />
		<%= f.text_field :comentario %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
	<% end %>
<% end %>

app/views/trocas/edit.html.erb
<h1>Editing troca</h1>

<%= render 'form' %>

<%= link_to 'Show', @troca %> |
<%= link_to 'Back', trocas_path %>

app/views/trocas/index.html.erb
<h1>Solicitações recebidas</h1>

<table border="0">
  <tr>
    <th>Livro solicitado</th>
    <th>Livro proposto</th>
    <th>Comentário</th>
  </tr>
  
<% @trocas = Troca.where({usuarioSolicitado_id: current_user.id})  %>
<% @trocas.each do |troca| %>
  <tr>
    <td><%= LivroBanco.find(troca.livroSolicitado_id).titulo %></td>
	<td><%= LivroBanco.find(troca.livroSolicitante_id).titulo %></td>
	<td><%= troca.comentario %></td>
	<% if troca.status == "0" %>
		<td><a href="/trocas/<%= troca.id %>/edit" >Aceitar</a>
		<td><%= link_to 'Rejeitar', troca, method: :delete%></td>
	<% end %>
	<% if troca.status == "1" %>
		<td><a href="/trocas/<%= troca.id %>/edit" >Informações</a>
	<% end %>
  </tr>
<% end %>
</table>

<h1>Solicitações feitas</h1>

<table border="0">
  <tr>
    <th>Livro solicitado</th>
    <th>Livro proposto</th>
    <th>Comentário</th>
  </tr>
  
<% @trocas = Troca.where({usuarioSolicitante_id: current_user.id})  %>
<% @trocas.each do |troca| %>
  <tr>
    <td><%= LivroBanco.find(troca.livroSolicitado_id).titulo %></td>
	<td><%= LivroBanco.find(troca.livroSolicitante_id).titulo %></td>
	<td><%= troca.comentario %></td>
	<td><%= link_to 'Cancelar', troca, method: :delete%></td>
  </tr>
<% end %>
</table>

app/views/trocas/new.html.erb
<h1>Nova solicitação de troca</h1>

<%= render 'form' %>

app/views/trocas/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<b>Seu Livro:</b>
	<% if @troca.usuarioSolicitante_id == current_user.id %>
	  <%= LivroBanco.find(@troca.livroSolicitante_id).titulo %>
	<% end %>
	<% if @troca.usuarioSolicitado_id == current_user.id %>
	  <%= LivroBanco.find(@troca.livroSolicitado_id).titulo %>
	<% end %>
</p>
<p>
	<b>Livro proposto:</b>
	<% if @troca.usuarioSolicitante_id == current_user.id %>
	  <%= LivroBanco.find(@troca.livroSolicitado_id).titulo %>
	<% end %>
	<% if @troca.usuarioSolicitado_id == current_user.id %>
	  <%= LivroBanco.find(@troca.livroSolicitante_id).titulo %>
	<% end %>
</p>
<p>
  <b>Comentário:</b>
  <%= @troca.comentario %>
</p>
<p>
  <b>Status:</b>
  <% if @troca.status == "0"%>
	Aberto
  <% end %>
  <% if @troca.status == "1"%>
		Aprovado
  <% end %>
</p>
<p>
	<% if @troca.status == "1"%>
		<b>Endereço para envio:</b>
		<% if @troca.usuarioSolicitante_id == current_user.id %>
			<% @usuario =  User.find(@troca.usuarioSolicitado_id) %>
			<%= @usuario.estado %>, <%= @usuario.cidade %>, <%= @usuario.endereco %>.
		<% end %>
		<% if @troca.usuarioSolicitado_id == current_user.id %>
			<% @usuario =  User.find(@troca.usuarioSolicitante_id) %>
			<%= @usuario.estado %>, <%= @usuario.cidade %>, <%= @usuario.endereco %>.
		<% end %>
	<% end %>
</p>