config/routes.rb
TrocaLivro::Application.routes.draw do
  resources :trocas

  resources :usuariolivros

  devise_for :users

  get "pages/index"

  get "login/login"

  resources :livro_bancos

  resources :usuarios
  

  

	match ':controller(/:action(/:id))(.:format)'
	root :to => "geral#index"
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :bairro, :cep, :cidade, :email, :endereco, :estado, :nome, :senha, :sexo, :telefoneCelular, :telefoneFixo
  
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario foi criado com sucesso.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
  
  # GET /sobre
  def teste
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :senha %><br />
    <%= f.password_field :senha %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br />
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br />
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :cep %><br />
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :bairro %><br />
    <%= f.text_field :bairro %>
  </div>
  <div class="field">
    <%= f.label :Telefone_Fixo %><br />
    <%= f.text_field :telefoneFixo %>
  </div>
  <div class="field">
    <%= f.label :Telefone_Celular %><br />
    <%= f.text_field :telefoneCelular %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editar usuario</h1>

<%= render 'form' %>

<%= link_to 'Mostar', @usuario %> |
<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Lista de usuarios</h1>
<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Cidade</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

</table>

<br />

app/views/usuarios/new.html.erb
<h1>Novo usuario</h1>

<%= render 'form' %>

<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @usuario.nome %>
</p>
<p>
  <b>Sexo:</b>
  <%= @usuario.sexo %>
</p>
<p>
  <b>Email:</b>
  <%= @usuario.email %>
</p>
<p>
  <b>Cidade:</b>
  <%= @usuario.cidade %>
</p>
<p>
  <b>Estado:</b>
  <%= @usuario.estado %>
</p>
<p>
  <b>Endereco:</b>
  <%= @usuario.endereco %>
</p>
<p>
  <b>Cep:</b>
  <%= @usuario.cep %>
</p>
<p>
  <b>Bairro:</b>
  <%= @usuario.bairro %>
</p>
<p>
  <b>Telefone fixo:</b>
  <%= @usuario.telefoneFixo %>
</p>
<p>
  <b>Telefone celular:</b>
  <%= @usuario.telefoneCelular %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/teste.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @usuario.nome %>
</p>
<p>
  <b>Sexo:</b>
  <%= @usuario.sexo %>
</p>
<p>
  <b>Email:</b>
  <%= @usuario.email %>
</p>
<p>
  <b>Cidade:</b>
  <%= @usuario.cidade %>
</p>
<p>
  <b>Estado:</b>
  <%= @usuario.estado %>
</p>
<p>
  <b>Endereco:</b>
  <%= @usuario.endereco %>
</p>
<p>
  <b>Cep:</b>
  <%= @usuario.cep %>
</p>
<p>
  <b>Bairro:</b>
  <%= @usuario.bairro %>
</p>
<p>
  <b>Telefone fixo:</b>
  <%= @usuario.telefoneFixo %>
</p>
<p>
  <b>Telefone celular:</b>
  <%= @usuario.telefoneCelular %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Voltar', usuarios_path %>